# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d3a77fe0-cde4-4b01-860d-9132cce170fc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a8f1e83c-8414-4465-a7d1-496a6c330e2e".device = "/dev/disk/by-uuid/a8f1e83c-8414-4465-a7d1-496a6c330e2e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D7C9-8C23";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/c67597ab-5b3b-47d3-8872-6a1a907ed7f8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9f68df2f-3cf8-4495-9865-187dd83d5ab2".device = "/dev/disk/by-uuid/9f68df2f-3cf8-4495-9865-187dd83d5ab2";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/32e19cea-5555-4f37-96e3-11515f3b1102";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cb6538c2-63c6-48ef-8193-caa1032ef222".device = "/dev/disk/by-uuid/cb6538c2-63c6-48ef-8193-caa1032ef222";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cdc13a51-18a5-4569-a0c9-b589b14449fe"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
